import { parseArgs } from "util";
import { spawn } from "child_process";
import { mkdirSync, existsSync, writeFileSync, readFileSync, readdirSync } from "fs";
import * as path from "path";
import { summarizeCorpusQuality } from "../engine/replay/corpus-quality.ts";
import type { PairManifest } from "../engine/replay/pair-manifest.ts";
import type { CalibrationRecord } from "../engine/replay/calibration-extractor.ts";
import type { CalibrationGlobalReadiness } from "../engine/replay/calibration-readiness-gate.ts";

const { values } = parseArgs({
  args: Bun.argv,
  options: {
    "pairs-dir": { type: "string", default: "data/pairs" },
    "out-dir": { type: "string" },
    variants: { type: "string", multiple: true, default: ["late-entry", "late-entry-flow-aware", "fair-value-maker"] },
    "strategy-lab-timeout-ms": { type: "string", default: "180000" },
    "min-valid-pairs": { type: "string", default: "1" },
    "fail-on-readiness-block": { type: "boolean", default: false },
    "dry-run": { type: "boolean" },
  },
  strict: true,
  allowPositionals: true,
});

async function runProcess(cmd: string, args: string[]): Promise<{ code: number | null }> {
  return new Promise((resolve) => {
    console.log(`\n> ${cmd} ${args.join(" ")}`);
    const p = spawn(cmd, args, { stdio: "inherit" });
    p.on("close", (code) => resolve({ code }));
    p.on("error", () => resolve({ code: null }));
  });
}

async function main() {
  const outDir = values["out-dir"] as string;
  if (!outDir) {
    console.error("Missing --out-dir");
    process.exit(1);
  }
  
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  const pairsDir = values["pairs-dir"] as string;
  const minValidPairs = parseInt(values["min-valid-pairs"] as string, 10);

  const manifests = [];
  if (existsSync(pairsDir)) {
    const files = readdirSync(pairsDir).filter(f => f.endsWith(".pair.json"));
    for (const f of files) {
      const p = path.join(pairsDir, f);
      manifests.push({ path: p, manifest: JSON.parse(readFileSync(p, "utf8")) as PairManifest });
    }
  }

  const validManifests = manifests.filter(m => m.manifest.pairValidity === "valid");
  if (validManifests.length < minValidPairs && !values["dry-run"]) {
    console.error(`Found ${validManifests.length} valid pairs, but min-valid-pairs is ${minValidPairs}. Aborting.`);
    process.exit(1);
  }

  const slJson = path.join(outDir, "calibration-summary.json");
  const calJsonl = path.join(outDir, "calibration.jsonl");
  const auditJson = path.join(outDir, "calibration-audit.json");
  const readinessJson = path.join(outDir, "readiness.json");
  const readinessMd = path.join(outDir, "readiness.md");
  const corpusJson = path.join(outDir, "corpus-summary.json");
  const finalMd = path.join(outDir, "final-report.md");

  if (values["dry-run"]) {
    console.log("[Dry Run] Skipping actual execution. Writing mock final report.");
    writeFileSync(finalMd, "# Pipeline Dry Run Complete\n\nNo live behavior was changed.");
    process.exit(0);
  }

  console.log("\n=== STEP 1: Running Strategy Lab and Extracting Calibration Records ===");
  const slArgs = [
    "scripts/run-strategy-lab-paired-corpus.ts",
    "--pairs-dir", pairsDir,
    "--timeout-ms", values["strategy-lab-timeout-ms"] as string,
    "--out-json", slJson,
    "--out-calibration-jsonl", calJsonl,
    "--variants", ...values.variants as string[]
  ];
  
  let res = await runProcess("bun", slArgs);
  if (res.code !== 0) {
    console.error("Strategy lab failed.");
    process.exit(1);
  }

  if (!existsSync(calJsonl)) {
    console.error("No calibration records were generated by Strategy Lab.");
    process.exit(1);
  }

  console.log("\n=== STEP 2: Running Calibration Audit ===");
  const auditArgs = [
    "scripts/audit-offline-calibration.ts",
    "--input", calJsonl,
    "--out-json", auditJson,
  ];
  res = await runProcess("bun", auditArgs);
  if (res.code !== 0) {
    console.error("Calibration audit failed.");
    process.exit(1);
  }

  console.log("\n=== STEP 3: Evaluating Readiness Gates ===");
  const readArgs = [
    "scripts/evaluate-calibration-readiness.ts",
    "--audit-json", auditJson,
    "--out-json", readinessJson,
    "--out-md", readinessMd,
  ];
  res = await runProcess("bun", readArgs);
  if (res.code !== 0) {
    console.error("Readiness evaluation failed.");
    process.exit(1);
  }

  console.log("\n=== STEP 4: Summarizing Corpus Quality ===");
  
  let records: CalibrationRecord[] = [];
  try {
    const content = readFileSync(calJsonl, "utf-8");
    for (const line of content.split("\n")) {
      if (!line.trim()) continue;
      records.push(JSON.parse(line));
    }
  } catch (err) {
    console.error("Failed to read calibration jsonl for summary.");
  }

  let readinessObj: CalibrationGlobalReadiness | undefined;
  try {
    readinessObj = JSON.parse(readFileSync(readinessJson, "utf8"));
  } catch (err) {
    console.error("Failed to read readiness json for summary.");
  }

  // Hardcode defaults based on prompt 8R
  const thresholds = { minTotalRecords: 5000, minTradePrintBackedRecords: 2000 };
  const quality = summarizeCorpusQuality(manifests, records, thresholds);
  writeFileSync(corpusJson, JSON.stringify(quality, null, 2));

  console.log("\n=== STEP 5: Writing Final Pipeline Report ===");

  let md = `# Corpus Calibration Pipeline Report\n\n`;
  md += `## Pipeline Status\n`;
  md += `- **Readiness Decision**: ${readinessObj?.globalDecision?.toUpperCase() || "UNKNOWN"}\n`;
  
  const isReady = readinessObj?.globalDecision === "paper_candidate";
  if (isReady) {
    md += `- The corpus IS READY for tuning.\n`;
  } else {
    md += `- The corpus IS NOT READY for tuning.\n`;
    md += `- Readiness remains blocked.\n`;
  }

  md += `\n## Candidate Status\n`;
  if (readinessObj) {
    const paper = readinessObj.candidates.filter(c => c.decision === "paper_candidate");
    const research = readinessObj.candidates.filter(c => c.decision === "research_only");
    const blocked = readinessObj.candidates.filter(c => c.decision === "blocked");
    
    if (paper.length > 0) md += `- Found ${paper.length} paper candidates.\n`;
    else md += `- No candidates are paper_candidate.\n`;
    
    if (paper.length === 0) md += `- All candidates are blocked or research_only.\n`;
  }

  md += `\n## Missing Thresholds\n`;
  if (quality.readinessThresholdProgress) {
    const p = quality.readinessThresholdProgress;
    if (p.totalRecords.current < p.totalRecords.required) {
      md += `- Total Records: ${p.totalRecords.current} / ${p.totalRecords.required}\n`;
    }
    if (p.tradePrintBacked.current < p.tradePrintBacked.required) {
      md += `- Trade-Print-Backed Records: ${p.tradePrintBacked.current} / ${p.tradePrintBacked.required}\n`;
    }
  }

  md += `\n## Explicit Non-Claims\n`;
  md += `- No live behavior was changed.\n`;
  md += `- No profitability is claimed.\n`;

  writeFileSync(finalMd, md);
  console.log(`Wrote final report to ${finalMd}`);

  if (values["fail-on-readiness-block"] && readinessObj?.globalDecision === "blocked") {
    console.error("Pipeline failing because readiness decision is blocked.");
    process.exit(1);
  }
}

main().catch(console.error);
